version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.7.1"
python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true
